# Generated by Django 5.1.5 on 2025-01-28 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.ImageField(default='logos/default.jpg', upload_to='logos'),
        ),
    ]
