# Generated by Django 5.1.5 on 2025-01-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.SmallIntegerField(choices=[(1, 'Initiated'), (2, 'Confirmed'), (3, 'Paid'), (-1, 'Cancelled')], default=1),
        ),
    ]
