# Generated by Django 5.1.5 on 2025-02-06 19:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='key',
            field=models.UUIDField(blank=True, default=uuid.uuid4, unique=True),
        ),
    ]
